const express=require("express");
const router=express.Router();
const User=require("../models/user.js");
const wrapasync = require("../utils/wrapasync.js");
const passport = require("passport");
const { saveRedirectUrl } = require("../middlewares");
const userController=require("../controllers/user.js");
router.get("/signup",userController.getSignedForm);
router.post("/signup",wrapasync(userController.signup));
router.get("/login",userController.getLogin);
router.post("/login",saveRedirectUrl,passport.authenticate('local', { failureRedirect: '/login',failureFlash:true },),(userController.login));
router.get("/logout",userController.logout);
module.exports=router;